// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/_middleware.ts";
import * as $1 from "./routes/auth/_middleware.ts";
import * as $2 from "./routes/auth/secret.tsx";
import * as $3 from "./routes/index.tsx";
import * as $4 from "./routes/login.tsx";
import * as $5 from "./routes/logout.tsx";
import * as $6 from "./routes/signup.tsx";

const manifest = {
  routes: {
    "./routes/_middleware.ts": $0,
    "./routes/auth/_middleware.ts": $1,
    "./routes/auth/secret.tsx": $2,
    "./routes/index.tsx": $3,
    "./routes/login.tsx": $4,
    "./routes/logout.tsx": $5,
    "./routes/signup.tsx": $6,
  },
  islands: {},
  baseUrl: import.meta.url,
  config,
};

export default manifest;
